---
title: Jessica Chapman Portfolio
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: jesseechapman@gmail.com
description: Jess Portfolio of work
baseurl: "/pages"
url: jesscee.github.io
markdown: kramdown
exclude:
- node_modules
- gulpfile.js
- package.json
- pancake
plugins:
- jekyll-minifier
jekyll-minifier:
  exclude:
  - assets/*/*.css
  - "*.min.*"
  - assets/*/*.js
  - manifest.yml
  - Staticfile
